### ISSUE TITLE
Support `TriangularToeplitz(Float64[],:U)`

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMatrices/ToeplitzMatrices.jl#22]
`TriangularToeplitz(Float64[],:U)` currently gives an unreadable error.  I think it should be supported (to represent a 0 x 0 matrix), or otherwise given a better error.

Supporting it will take some thought about how to construct `tmp`.

**Comment by andreasnoack** [comment]
I think the main challenge is the dft since we could just condition https://github.com/JuliaMatrices/ToeplitzMatrices.jl/blob/master/src/ToeplitzMatrices.jl#L366-L373 on `n>0`. We might want to avoid the cost of creating the dft for small `n>0` so maybe a way forward is to make that field `Nullable{Base.DFT.FFTW.cFFTWPlan{Complex{T},-1,true,1}}` or something like that.

**Comment by dlfivefifty** [comment]
Yes I think that's a good idea.  (I forgot about Nullable...)

**Comment by dlfivefifty** [comment]
For my usage, I think I can work around this by using Nullable{TriangularToeplitz}.

**Comment by dkarrasch** [comment]
The following works, so I believe the issue has been solved some time ago.

```julia
julia> U = TriangularToeplitz(Float64[],:U)
0×0 TriangularToeplitz{Float64}

julia> x = Float64[]
Float64[]

julia> U*x
Float64[]
```
